### PR TITLE
Add extra_float_digits parameter parsing

### PR DESCRIPTION
**Pull request by sehrope**
This PR pulls `extra_float_digits` from the query portion of the connection URI and if exists, populates it on the returned config object.

This is needed in node-postgres to eventually allow specifying a custom value for it.

### CODE REVIEW

**Comment by phated** [comment]
I'd like some follow up by the maintainers on your node-postgres issue before I merge this.

@brianc thoughts?

**Comment by elmigranto** [comment]
Let's merge #7 instead? White-listing isn't best option here overall, I think, since server rejects invalid options already, and it is substantially more hassle trying to keep up with [all the params supported](https://www.postgresql.org/docs/9.5/static/libpq-connect.html#LIBPQ-CONNSTRING) (and changing them in short time).

**Comment by caub** [comment]
#11 does this more generally

**Comment by monteslu** [comment]
@sehrope  @elmigranto @caub You good with closing this since #11 has been merged?

**Comment by hjr3** [comment]
@sehrope Closing this as I think this issue is solved. Please ping back if there is still an outstanding issue.

**Pull request closed without merging**
