### PR TITLE
Integrating generic connection-string

### LINKED ISSUE #14: Doesn't respect host in query parameters
Currently the following connection string doesn't get parsed properly:

```text
postgresql:///test?host=%2Ftmp%2Fephemeralpg.goZMBg
```

It was generated by the tool [ephemeralpg](http://ephemeralpg.org) and seems to work with other client...

### PR DESCRIPTION
**Pull request by vitaly-t**
* Implements #13 (which in turn fixes #14 + #23), to close all open issues as of today. Plus it fixes all tests to work on Windows.
* This requires a major version bump, and the PR also upps the version to 3.0.0.
* All syntax updated to ES6, since even the driver doesn't support ES5 anymore.

---

Many tests now can be retired, because this library doesn't do the parsing anymore. But for now I kept as many tests as I could.

This implementation uses [connection-string] underneath, while implementing the functionality as close as possible to the original, and to keep it mostly compatible with the existing driver.

This first version ignores multi-host support, but makes it very easy to activate, once the driver starts supporting it, since [connection-string] supports it out-of-the-box.

However, some functionality had to be changed, and below is the list of all breaking changes...

* Unix sockets support is now much simpler: the host name either ends with `.sock`, or contains `/` after decoding.
* Special symbols in the user name or password need to be URL-encoded, the same as any other part of the URL, as it must be compliant with the [URL Connection String standard](https://www.ietf.org/rfc/rfc3986.txt).
* Since `database` now always comes from the first path segment, there is no more need in custom parameter `db`. In the simplest form, `/dbname` results in the database set correctly.
* Minor changes as to the short-syntax expectations now reflect what the URL spec requires. For example, passing in just `some-name` sets the host, not the database name. For the database shortest syntax it is `/some-name`, and for just host + database, it is `host/database`. [See more examples here](https://github.com/vitaly-t/connection-string/wiki).

For other references, see [connection-string]. It supports abbreviations, defaults, string generation, etc, many nice features.

**UPDATE**

I have added a good usage example - [connection-string-demo](https://github.com/vitaly-t/connection-string-demo).

[connection-string]:https://github.com/vitaly-t/connection-string

### CODE REVIEW

**Comment by vitaly-t** [comment]
@monteslu Do you think this is possible? :smile:

**Comment by abowerman** [comment]
Will review, is this still work in progress?

**Comment by vitaly-t** [comment]
>  is this still work in progress?

@abowerman nope, it is all done and good to go! :)

**Comment by vitaly-t** [comment]
@abowerman I have made some important improvements as to how Unix sockets are supported, both here and in the [connection-string]. It is so much simpler, and more logical...

Any host name that either ends with `.sock` or contains `/` after decoding is recognized as a Unix socket.

[connection-string]:https://github.com/vitaly-t/connection-string

**Comment by hjr3** [comment]
> I have made some important improvements as to how Unix sockets are supported, both here and in the connection-string. It is so much simpler now, and more logical.

@vitaly-t is this a breaking change?

**Comment by vitaly-t** [comment]
@hjr3 Considering that `node-postgres` is still stuck with v0.1.3, there won't be any progress, unless we make it :wink:

**Comment by vitaly-t** [comment]
@abowerman Is it ok to merge it now?

**Comment by abowerman** [comment]
Looks like you are still making changes here.

**Comment by vitaly-t** [comment]
@abowerman I've been making improvements to the library, and here only updating dependencies, nothing else. This shouldn't stop you from merging the PR ;)

**Comment by vitaly-t** [comment]
@abowerman Just checking back, as it's been 12 days since...

**Comment by vitaly-t** [comment]
@abowerman just pinging ;)

**Comment by vitaly-t** [comment]
How come we lost all the response here after...?

@hjr3 @abowerman Could someone, please review and merge it?

**Comment by abowerman** [comment]
Am reluctant to introduce dependencies and breaking changes here. This is fairly heavily used and currently does not have any dependencies. @hjr3 @monteslu Thoughts?

**Comment by vitaly-t** [comment]
For one thing, it is marked as version 3.0.0, within the PR itself. And for another, [the driver has been stuck on the ancient version](https://github.com/brianc/node-postgres/blob/master/package.json#L24) anyhow. So it won't break anything, if we just follow the major version increment.

**Comment by hjr3** [comment]
This change guts the code base and makes `pg-connection-string` a thin wrapper around [connection-string][cs]. The code is looks fine, but there is something that just feels wrong about it. 

This is an old repository. It is depended on by a lot of people. The repository itself has a reputation behind it. There is a (loose) governance model. By merging this PR, then we give all that up. Any bug or feature request will have to be redirected to [connection-string][cs]. The go-forward role for the current maintainers will only be bumping the version of [connection-string][cs] periodically.

Maybe [connection-string][cs] is the better option though! @vitaly-t is very motivated to improve the current state of connection string parsing and this repository has been pretty quiet. If [connection-string][cs] is the better option, we should probably deprecate this repository and redirect people to [connection-string](https://github.com/vitaly-t/connection-string). No reason to make a `3.0.0` version of this repository.

My vote is to update the README that this repository is deprecated, the `.2.x.x` branch will receive security updates only and people should start migrating to [connection-string][cs].

[cs]: https://github.com/vitaly-t/connection-string

**Comment by vitaly-t** [comment]
@hjr3 The important thing, issues around the lack of code consolidation keep rising, but nothing happens. [Here's the last one, just from today](https://github.com/brianc/node-postgres/issues/1949), that's why I'm trying to revive it again.

**Comment by hjr3** [comment]
Yup, I hear you. I am all for node-postgres updating its dependency to be on `connection-string` instead.

**Comment by vitaly-t** [comment]
As part of moving all my projects toward native TypeScript implementations, I've just published a pre-release update for this one - [3.0.0-Beta.0](https://github.com/vitaly-t/connection-string/releases/tag/3.0.0-Beta.0).

**Comment by vitaly-t** [comment]
@abowerman, @hjr3 

Updated to use the new 3.x version of [connection-string], re-done in TypeScript.

[connection-string]:https://github.com/vitaly-t/connection-string

**Comment by zxqfox** [comment]
Hello fellow. Am I right that better to migrate `node-postgres` to `connection-string` and keep `pg-connection-string` as is?
I have some time to work on it and deciding what to do

**Comment by vitaly-t** [comment]
@zxqfox For the lack of the progress either way, to move toward a better generic approach, I no longer want to advocate any kind of integration. For people who want to use `connection-string`, they can just do so independently, and generate a connection object from it to be passed into the driver, as shown within the [Adapters](https://github.com/vitaly-t/connection-string/wiki/Adapters).

**Pull request closed without merging**
