### PR TITLE
Question marks in passwords

### PR DESCRIPTION
**Pull request by webnard**
Enables the use of question marks in Postgres connection string passwords

### CODE REVIEW

**Comment by phated** [comment]
Not sure how I feel about this.  Was there an issue opened on node-postgres about this?

cc @brianc

**Comment by webnard** [comment]
@phated, No, AFAIK no issue was ever opened. I was using a module (https://github.com/evs-chris/node-postgres-gen) that kind of circuitously used this library to parse connection strings. My database connections were timing out, and I realized that they weren't being parsed correctly due to a question mark in the password. I had no problems connecting to Postgres using psql, and Postgres had no qualms setting a password with a question mark, but the URL parsing took the question mark to be the beginning of a query string.

Eventually I just changed the password to something that didn't utilize that character, so everything is hunky-dory now. Thought this might save some future headaches, though, in case anyone ever ended up with the same problem.

**Comment by phated** [comment]
That's fair.  I wonder if we could just escape the connection string better or tweak the regexp.  Just seems like the implementation is complex for the support.

**Comment by webnard** [comment]
Agreed. It's not a very concise solution at all. If I get some free time I'm happy to revisit the code and try to consolidate things.

**Comment by 2fast2fourier** [comment]
I've been looking at this, and I'm not sure if we should solve this with a complicated parsing step. 

Technically, any URI with a username/password containing unescaped reserved characters is malformed, and I don't think the library should be expected to accept and fix a broken URL. The general expectation is to encode the username and password fields prior to building the url: `postgres://usern%40me:pass%3Ford@localhost/test`. Once the URL is formed, it's significantly harder to determine where the username and password especially if we potentially have unescaped reserved characters in the content.

Unfortunately I don't think this current solution will work out, and might even introduce more bugs than it'll fix. The `parsePostgresURL` method doesn't seem to handle potential edge-cases very well (extra `@`, `:`, other weirdness), and only supports `postgresql://` when `postgres://` which is a valid alternative.

I think for simplicity's sake, we shouldn't really attempt to repair malformed urls. There is some existing functionality that attempts to repair unescaped spaces, but extending that to cover reserved characters like `?` and `@` would add considerable complexity due to their role in the URI structure. I would argue that we should reject obviously malformed URLs more loudly, but since this is only a passthrough library we can't really make that decision without potentially harming client implementations.

@webnard Can you verify that encoded url strings work in your situation? I'm going to close this issue, but if you run into any problems please don't hesitate to open an issue.

**Comment by phated** [comment]
I agree with @2fast2fourier on this

**Comment by webnard** [comment]
> Technically, any URI with a username/password containing unescaped reserved characters is malformed, and I don't think the library should be expected to accept and fix a broken URL

D'oh! I hadn't even thought about that. You're right: encoded strings seem to work fine. Apparently [libpq's implementation of URI parsing](http://doxygen.postgresql.org/fe-connect_8c_source.html#l04717) per [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt) (which it references) is incorrect, as it looks like it only checks for `@` as an end-of-password delimiter.

Thanks for the help.

**Pull request closed without merging**
